### ISSUE TITLE
支持拦截器吗？

### ISSUE THREAD

**Issue by guozhiqiang123** [limuyang2/okcronet#2]
我们对接口数据加密解密，一般是在拦截器里面完成的，这样不用每个接口请求的时候都去主动调用一遍加密解密方法，如果支持拦截器，那基本很容易从okhttp迁移过来。
不支持是否支持？

**Comment by 250king** [comment]
我这边也有类似的需求，就要在请求之前将Token塞进请求头，如果贵作者没打算弄拦截器，那有没有别的解决方案？

**Comment by limuyang2** [comment]
> 我这边也有类似的需求，就要在请求之前将Token塞进请求头，如果贵作者没打算弄拦截器，那有没有别的解决方案？

是有拦截器功能
